### ISSUE TITLE
Configure TLS/SSL for OSO Website

### ISSUE THREAD

**Issue by KeithSSmith** [open-science-org/oso.github.io#10]
Acquire and apply CA cert to ensure we are adhering to best practices to ensure visitors traffic is trusted and encrypted.

**Comment by abinashk** [comment]
@KeithSSmith @bikos @himalayajung I can get a CA cert from https://letsencrypt.org Let me know if any of you don't like or have any concern about letsencrypt.org

**Comment by KeithSSmith** [comment]
I had actually just found out about Lets Encrypt this week and thought it might be a good fit here.  Especially when the alternative is paying one of the bigger CA's.
