### ISSUE TITLE
Update Social Media Links with Medium, Reddit, and Chat Accounts

### ISSUE THREAD

**Issue by KeithSSmith** [open-science-org/oso.github.io#8]
Medium and Reddit should be straight forward once the subreddit is created, issue filed here: [Admin Issue 3](https://github.com/open-science-org/admin/issues/3)

For the chat account selection find the issue here: [Admin Issue 4](https://github.com/open-science-org/admin/issues/4)

**Comment by oso-network** [comment]
@abinashk @bikos 
Medium account @openscienceorg and subreddit /r/openscienceorg have been created
